name: Fox RP Auto-Builder

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Customize Fox RP
        run: |
          # 1. Меняем название приложения
          find . -type f -name "strings.xml" -exec sed -i 's/Open SAMP/Fox RP/g' {} +
          
          # 2. Меняем ID пакета везде
          find . -type f -name "*.gradle" -exec sed -i 's/com.umnicode.samp/com.foxrp.launcher/g' {} +
          find . -type f -name "*.xml" -exec sed -i 's/com.umnicode.samp/com.foxrp.launcher/g' {} +
          find . -type f -name "*.java" -exec sed -i 's/com.umnicode.samp/com.foxrp.launcher/g' {} +

          # 3. Красим в оранжевый неон (заменяем стандартный цвет)
          find . -type f -name "colors.xml" -exec sed -i 's/#FF5722/#FF8C00/g' {} +

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload Fox RP Launcher
        uses: actions/upload-artifact@v4
        with:
          name: FoxRP_Launcher_Build
          path: app/build/outputs/apk/debug/app-debug.apk
          
