name: Fox RP Auto-Builder

on:
  workflow_dispatch: # Позволяет запускать сборку кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Авто-кастомизация: меняем название и пакет
      - name: Customize Project
        run: |
          # Меняем название приложения
          sed -i 's/Open SAMP/Fox RP/g' app/src/main/res/values/strings.xml
          # Меняем ID пакета
          find . -type f -name "*.gradle" -exec sed -i 's/com.umnicode.samp/com.foxrp.launcher/g' {} +
          # Меняем основной оранжевый цвет в ресурсах (неон)
          sed -i 's/#FF5722/#FF8C00/g' app/src/main/res/values/colors.xml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload Fox RP Launcher
        uses: actions/upload-artifact@v3
        with:
          name: FoxRP_Beta_Build
          path: app/build/outputs/apk/debug/app-debug.apk
          
